[package]
name = "btree"
version = "0.1.0"
authors = ["William Speirs <bill.speirs@gmail.com>"]

[dependencies]
serde = {  version = "1.0.210", features = ["derive"] }
itertools = "0.13.0"
rand = "0.8.5"
bincode = "1.3.3"
